-- Optional demo data. Never apply this file to a real customer installation.
begin;
insert into public.core_restaurants(id,slug,name,config) values(
 '00000000-0000-4000-8000-000000000001','demo-restaurant','NADAV Core Demo Restaurant',
 '{"identity":{"slug":"demo-restaurant","name":"NADAV Core Demo Restaurant","tagline":"Una cocina independiente sobre NADAV Core","locale":"es-AR","currency":"ARS","timeZone":"America/Argentina/Buenos_Aires"},"ordering":{"pickup":true,"delivery":true,"minimumOrder":5000,"baseDeliveryFee":1800},"payments":{"cash":true,"transfer":true,"mercadoPago":true},"printing":{"printNode":true,"paper":"80"},"features":{"delivery":true,"pickup":true,"mercadoPago":true,"cash":true,"transfer":true,"stock":true,"promotions":true,"customers":true,"analytics":true,"printNode":true},"hours":{"mon":{"open":true,"from":"11:00","to":"23:00"},"tue":{"open":true,"from":"11:00","to":"23:00"},"wed":{"open":true,"from":"11:00","to":"23:00"},"thu":{"open":true,"from":"11:00","to":"23:00"},"fri":{"open":true,"from":"11:00","to":"00:30"},"sat":{"open":true,"from":"11:00","to":"00:30"},"sun":{"open":true,"from":"11:00","to":"23:00"}}}'::jsonb
);
insert into public.core_catalog_state(restaurant_id,data) values(
 '00000000-0000-4000-8000-000000000001',
 '{"categories":[{"id":"cat-kitchen","name":"Cocina","position":1},{"id":"cat-drinks","name":"Bebidas","position":2}],"products":[{"id":"product-01","categoryId":"cat-kitchen","name":"Sándwich de estación","description":"Pan artesanal, vegetales asados y queso.","price":9800,"promotionalPrice":null,"available":true,"stock":30,"modifierGroups":[{"id":"bread","name":"Pan","min":1,"max":1,"options":[{"id":"country","name":"De campo","price":0,"available":true},{"id":"focaccia","name":"Focaccia","price":900,"available":true}]}]},{"id":"product-02","categoryId":"cat-kitchen","name":"Pasta del día","description":"Pasta fresca con salsa de estación.","price":12400,"promotionalPrice":11200,"available":true,"stock":20,"modifierGroups":[]},{"id":"product-03","categoryId":"cat-drinks","name":"Limonada","description":"Limón, menta y jengibre.","price":3900,"promotionalPrice":null,"available":true,"stock":null,"modifierGroups":[]}],"promotions":[{"id":"promo-welcome","name":"Bienvenida","code":"CORE10","type":"percentage","value":10,"productIds":[],"active":true}],"deliveryZones":[{"id":"zone-center","name":"Centro","fee":1800,"active":true},{"id":"zone-north","name":"Zona norte","fee":2500,"active":true}]}'::jsonb
);
commit;
